import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:our_gym/All_courses/courses_screen.dart';

class ActivityScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    var size =MediaQuery.of(context).size;
    return Scaffold(
      body: Padding(
        padding:  EdgeInsets.only(top: 40.0),
        child: SingleChildScrollView(
          child: Column(
            children: [
              InkWell(
                onTap: (){
                  Get.to(CoursesScreen( 'Zumba', '''What is Zumba?
Zumba's most well-known and popular program is its namesake class, Zumba.\n
 This dance class features high- and low-intensity intervals that help improve cardiovascular fitness while also enhancing balance,
  coordination, agility, and to some degree, strength through the application of beginner-accessible choreography.''',));
                },
                child: Container(
                  width: double.infinity,
                  height: 180,
                  child:  Center(
                    child: Stack(
                      children: [
                        Image(
                          image: AssetImage(
                            'assets/images/zumba.webp',

                          ),
                          width: double.infinity,
                          height: 180,
                          fit: BoxFit.fill,
                        ),
                        Container(

                          color: Colors.white54,
                        ),
                        Padding(
                          padding: const EdgeInsets.only(top: 88.0,left: 150),
                          child: Text(
                            "ZUMBA",
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 26
                            ),

                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              InkWell(
                onTap: (){
                  Get.to(CoursesScreen( 'Workout',
                  '''What is Workout?\n
A workout is a physical exercise routine that is designed to improve or maintain fitness levels, build strength, 
increase endurance, or achieve specific health and fitness goals. Workouts can consist of a variety of exercises and movements, 
such as weightlifting, cardio, yoga, pilates, and more. They can be performed at a gym, fitness center, outdoors, or in the comfort of
 your own home.
'''                      ,));
                },
                child: Container(
                  width: double.infinity,
                  height: 180,
                  child: Stack(
                    children: [
                      Image(
                        image: AssetImage(
                          'assets/images/workout.jfif',

                        ),
                        width: double.infinity,
                        height: 180,
                        fit: BoxFit.fill,
                      ),
                      Container(

                        color: Colors.white54,
                      ),
                      Center(
                        child: Text(
                            "WORKOUT",
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 26
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              InkWell(
                onTap: (){
                  Get.to(CoursesScreen( 'Weight', '''What is Weight training?\n
Weight training is a common type of strength training for developing the strength, size of skeletal muscles and maintenance of strength.
 It uses the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose the force generated by muscle through  
 concentric or eccentric contraction. ''',));

                },
                child: Container(

                  width: double.infinity,
                  height: 180,
                  child: Stack(
                    children: [
                      Image(
                        image: AssetImage(
                          'assets/images/weight.jfif',

                        ),
                        width: double.infinity,
                        height: 180,
                        fit: BoxFit.fill,
                      ),

                      Container(
                        color: Colors.white54,
                      ),
                      Center(
                        child: Text(
                          "Weight",
                          style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 26
                          ),

                        ),
                      ),
                    ],
                  ),
                ),
              ),

              InkWell(
                onTap: (){
                  Get.to(CoursesScreen('Cardio',
                  '''What Is Cardio?\n
Cardio exercise, which is sometimes referred to as aerobic exercise,
 is any rhythmic activity that raises your heart rate into your target heart rate zone. 
 This is the zone where you burn the most fat and calories.'''
                    ,));

                },
                child: Container(


                  width: double.infinity,
                  height: 180,
                  child:
                  Stack(
                    children: [
                      Image(
                        image: AssetImage(
                          'assets/images/cardio.jpg',

                        ),
                        width: double.infinity,
                        height: 180,
                        fit: BoxFit.fill,
                      ),
                      Container(

                        color: Colors.white54,
                      ),
                      Center(
                        child: Text(
                          "Cardio",
                          style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 26
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              InkWell(
                onTap: (){
                  Get.to(CoursesScreen( 'Yoga',
                  '''What is yoga?
Yoga is a Sanskrit word translated as “yoke” or “union.” To yoke means to draw together, to bind together; or to unite. Its aim is to yoke or create a union of the body, mind, soul, and universal consciousness.
 This process of uniting the physical, mental, emotional, and spiritual aspects of ourselves is what allows yogis to experience deep states of freedom,
  peace and self-realization.''',));

                },
                child: Container(

                  decoration: BoxDecoration(

                    color: Colors.greenAccent,
                  ),
                  width: double.infinity,
                  height: 180,
                  child: Stack(
                    children: [
                      Image(
                        image: AssetImage(
                          'assets/images/yoga.jfif',

                        ),
                        width: double.infinity,
                        height: 180,
                        fit: BoxFit.fill,
                      ),
                      Container(

                        color: Colors.white54,
                      ),
                      Center(
                        child: Text(
                          "Yoga",
                          style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 26
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

            ],
          ),
        ),
      ),
    );
  }
}
